spring:
  batch:
    job:
      names: CsvImportSkipJob
    jdbc:
      initialize-schema: always
      schema: classpath:org/springframework/batch/core/schema-postgresql.sql
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/sampledb
    username: postgres
    password: password

logging:
  level:
    '[com.example.BatchCsvImport]': debug